name: 'fintech_dbt'
version: '1.0.0'
config-version: 2

profile: 'fintech_dbt'

dbt-cloud:
  project-id: 70506183132573

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fintech_dbt:
    marts:
      core:
        +materialized: table
      finance:
        +materialized: table
seeds:
  fintech_dbt:
    nyse_holidays:
      +column_types:
        holiday_date: date
        holiday_name: string